export const TEMPLATES = [
  {
    id: "modern-1",
    title: "Modern Professional",
    description: "Clean two-column layout, great for experienced professionals.",
    previewImage: "/images/templates/SmrAI-Studio-Resume-A4.jpg",
    isPaid: true,
    isAvailable: true,
    badge: "Popular",
    category: "experienced",
  },
  {
    id: "bold-sidebar",
    title: "Bold Sidebar",
    description: "Strong left sidebar for contact & skills, content on the right.",
    previewImage: "/images/templates/1 (1).png",
    isPaid: true,
    isAvailable: true,
    badge: "New",
    category: "experienced",
  },
  {
    id: "minimal-1",
    title: "Simple & Minimal",
    description: "Single-column layout, perfect for fresher & minimalist profiles.",
    previewImage: "/images/templates/1 (2).png",
    isPaid: true,
    isAvailable: true,
    badge: "ATS Friendly",
    category: "fresher",
  },
  {
    id: "creative-gradient",
    title: "Creative Gradient",
    description: "Vibrant color bar headers and creative fonts for design roles.",
    previewImage: "/images/templates/1 (3).png",
    isPaid: true,
    isAvailable: true,
    badge: "Creative",
    category: "experienced",
  },
  {
    id: "corporate-clean",
    title: "Corporate Clean",
    description: "Blue-gray tones and clean structure suited for management roles.",
    previewImage: "/images/templates/1 (4).png",
    isPaid: true,
    isAvailable: false,
    badge: "Coming Soon",
    category: "experienced",
  },
  {
    id: "elegant-serif",
    title: "Elegant Serif",
    description: "Classic fonts and balanced spacing, great for academia or HR.",
    previewImage: "/images/templates/1 (5).png",
    isPaid: true,
    isAvailable: false,
    badge: "Coming Soon",
    category: "experienced",
  },
  {
    id: "tech-focused",
    title: "Tech Focused",
    description: "Monospace typography and clean blocks for developers and engineers.",
    previewImage: "/images/templates/tech.png",
    isPaid: true,
    isAvailable: true,
    badge: "Developer",
    category: "developer",
  },
  {
    id: "classic-border",
    title: "Classic Border",
    description: "Thin border layout with professional blue tones for all industries.",
    previewImage: "/images/templates/1 (7).png",
    isPaid: true,
    isAvailable: false,
    badge: "Coming Soon",
    category: "experienced",
  },
  {
    id: "ats-friendly",
    title: "ATS Friendly CV",
    description: "ATS-optimised developer template with semantic headings, clickable contact links, and correct parse order.",
    previewImage: "/images/templates/tech.png",
    isPaid: true,
    isAvailable: true,
    badge: "ATS Friendly",
    category: "ats-friendly",
  },
  {
    id: "ats-customer-service",
    title: "Customer Service",
    description: "ATS-ready template for customer service, call centre, and support roles. Highlights service achievements and core competencies.",
    previewImage: "/images/templates/SmrAI-Studio-Resume-A4.jpg",
    isPaid: true,
    isAvailable: true,
    badge: "ATS Friendly",
    category: "ats-friendly",
  },
  {
    id: "ats-sales",
    title: "Sales & Business Development",
    description: "Results-driven ATS template for sales professionals. Showcases revenue achievements, quotas, and client relationships.",
    previewImage: "/images/templates/1 (1).png",
    isPaid: true,
    isAvailable: true,
    badge: "ATS Friendly",
    category: "ats-friendly",
  },
  {
    id: "ats-marketing",
    title: "Marketing & Digital",
    description: "ATS-optimised for marketing professionals. Highlights campaigns, digital channels, brand growth, and analytics skills.",
    previewImage: "/images/templates/1 (2).png",
    isPaid: true,
    isAvailable: true,
    badge: "ATS Friendly",
    category: "ats-friendly",
  },
  {
    id: "ats-healthcare",
    title: "Healthcare & Nursing",
    description: "ATS template for nurses, doctors, and allied health professionals with Clinical Experience and Licenses & Certifications sections.",
    previewImage: "/images/templates/1 (3).png",
    isPaid: true,
    isAvailable: true,
    badge: "ATS Friendly",
    category: "ats-friendly",
  },
  {
    id: "ats-finance",
    title: "Finance & Accounting",
    description: "ATS-ready for accountants, analysts, and finance professionals. Highlights financial skills, software, and professional certifications.",
    previewImage: "/images/templates/1 (4).png",
    isPaid: true,
    isAvailable: true,
    badge: "ATS Friendly",
    category: "ats-friendly",
  },
  {
    id: "ats-teacher",
    title: "Teaching & Education",
    description: "ATS-friendly for teachers and educators. Features Teaching Experience, Teaching Certifications, and Professional Development sections.",
    previewImage: "/images/templates/1 (5).png",
    isPaid: true,
    isAvailable: true,
    badge: "ATS Friendly",
    category: "ats-friendly",
  },
  {
    id: "ats-hr",
    title: "Human Resources",
    description: "ATS-optimised for HR professionals. Showcases recruitment, employee relations, HR Competencies, and HR Certifications.",
    previewImage: "/images/templates/1 (6).png",
    isPaid: true,
    isAvailable: true,
    badge: "ATS Friendly",
    category: "ats-friendly",
  },
  {
    id: "ats-engineering",
    title: "Engineering",
    description: "ATS template for mechanical, civil, and electrical engineers. Highlights Engineering Projects, Technical Skills, and Certifications.",
    previewImage: "/images/templates/tech2.png",
    isPaid: true,
    isAvailable: true,
    badge: "ATS Friendly",
    category: "ats-friendly",
  },
  {
    id: "ats-admin",
    title: "Administrative & Office",
    description: "ATS-ready for administrative assistants, office managers, and coordinators. Highlights organisation, communication, and office skills.",
    previewImage: "/images/templates/1 (7).png",
    isPaid: true,
    isAvailable: true,
    badge: "ATS Friendly",
    category: "ats-friendly",
  },
  {
    id: "ats-legal",
    title: "Legal & Compliance",
    description: "ATS template for lawyers, paralegals, and compliance officers. Features Legal Experience, Bar Admissions, and Areas of Practice.",
    previewImage: "/images/templates/tech1.png",
    isPaid: true,
    isAvailable: true,
    badge: "ATS Friendly",
    category: "ats-friendly",
  },
  {
    id: "ats-logistics",
    title: "Logistics & Supply Chain",
    description: "ATS-optimised for supply chain, procurement, and logistics professionals. Highlights operations, vendor management, and efficiency gains.",
    previewImage: "/images/templates/SmrAI-Studio-Resume-A4.jpg",
    isPaid: true,
    isAvailable: true,
    badge: "ATS Friendly",
    category: "ats-friendly",
  },
  {
    id: "ats-hospitality",
    title: "Hospitality & Tourism",
    description: "ATS-ready for hotel, restaurant, and tourism professionals. Showcases Hospitality Experience, guest service skills, and certifications.",
    previewImage: "/images/templates/1 (1).png",
    isPaid: true,
    isAvailable: true,
    badge: "ATS Friendly",
    category: "ats-friendly",
  },
];

export function getTemplateById(id) {
  return TEMPLATES.find((t) => t.id === id) || TEMPLATES[0];
}

export function getAvailableTemplates() {
  return TEMPLATES.filter((t) => t.isAvailable);
}
